# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      
      # Entferne das '-G' Flag aus allen Compiler-Flags
      if config.build_settings['OTHER_CFLAGS']
        config.build_settings['OTHER_CFLAGS'] = config.build_settings['OTHER_CFLAGS'].gsub('-G', '')
      end
      if config.build_settings['OTHER_CPLUSPLUSFLAGS']
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = config.build_settings['OTHER_CPLUSPLUSFLAGS'].gsub('-G', '')
      end
      if config.build_settings['OTHER_CFLAGS_DEBUG']
        config.build_settings['OTHER_CFLAGS_DEBUG'] = config.build_settings['OTHER_CFLAGS_DEBUG'].gsub('-G', '')
      end
      if config.build_settings['OTHER_CFLAGS_RELEASE']
        config.build_settings['OTHER_CFLAGS_RELEASE'] = config.build_settings['OTHER_CFLAGS_RELEASE'].gsub('-G', '')
      end
      
      # Entferne das '-G' Flag aus allen Build-Settings
      config.build_settings.each do |key, value|
        if value.is_a?(String) && value.include?('-G')
          config.build_settings[key] = value.gsub('-G', '')
        end
      end
    end
  end
end
